// <auto-generated />
using System;
using System.Reflection;
using Aquiis.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Aquiis.Infrastructure.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class InspectionEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Aquiis.Core.Entities.Inspection",
                typeof(Inspection),
                baseEntityType,
                propertyCount: 68,
                navigationCount: 3,
                foreignKeyCount: 3,
                unnamedIndexCount: 4,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(BaseModel).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseModel).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));

            var actionItemsRequired = runtimeEntityType.AddProperty(
                "ActionItemsRequired",
                typeof(string),
                propertyInfo: typeof(Inspection).GetProperty("ActionItemsRequired", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<ActionItemsRequired>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2000);

            var bathroomSinkGood = runtimeEntityType.AddProperty(
                "BathroomSinkGood",
                typeof(bool),
                propertyInfo: typeof(Inspection).GetProperty("BathroomSinkGood", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<BathroomSinkGood>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var bathroomSinkNotes = runtimeEntityType.AddProperty(
                "BathroomSinkNotes",
                typeof(string),
                propertyInfo: typeof(Inspection).GetProperty("BathroomSinkNotes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<BathroomSinkNotes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var bathroomToiletGood = runtimeEntityType.AddProperty(
                "BathroomToiletGood",
                typeof(bool),
                propertyInfo: typeof(Inspection).GetProperty("BathroomToiletGood", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<BathroomToiletGood>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var bathroomToiletNotes = runtimeEntityType.AddProperty(
                "BathroomToiletNotes",
                typeof(string),
                propertyInfo: typeof(Inspection).GetProperty("BathroomToiletNotes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<BathroomToiletNotes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var bathroomTubShowerGood = runtimeEntityType.AddProperty(
                "BathroomTubShowerGood",
                typeof(bool),
                propertyInfo: typeof(Inspection).GetProperty("BathroomTubShowerGood", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<BathroomTubShowerGood>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var bathroomTubShowerNotes = runtimeEntityType.AddProperty(
                "BathroomTubShowerNotes",
                typeof(string),
                propertyInfo: typeof(Inspection).GetProperty("BathroomTubShowerNotes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<BathroomTubShowerNotes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var bathroomVentilationGood = runtimeEntityType.AddProperty(
                "BathroomVentilationGood",
                typeof(bool),
                propertyInfo: typeof(Inspection).GetProperty("BathroomVentilationGood", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<BathroomVentilationGood>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var bathroomVentilationNotes = runtimeEntityType.AddProperty(
                "BathroomVentilationNotes",
                typeof(string),
                propertyInfo: typeof(Inspection).GetProperty("BathroomVentilationNotes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<BathroomVentilationNotes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var calendarEventId = runtimeEntityType.AddProperty(
                "CalendarEventId",
                typeof(Guid?),
                propertyInfo: typeof(Inspection).GetProperty("CalendarEventId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<CalendarEventId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var carbonMonoxideDetectorsGood = runtimeEntityType.AddProperty(
                "CarbonMonoxideDetectorsGood",
                typeof(bool),
                propertyInfo: typeof(Inspection).GetProperty("CarbonMonoxideDetectorsGood", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<CarbonMonoxideDetectorsGood>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var carbonMonoxideDetectorsNotes = runtimeEntityType.AddProperty(
                "CarbonMonoxideDetectorsNotes",
                typeof(string),
                propertyInfo: typeof(Inspection).GetProperty("CarbonMonoxideDetectorsNotes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<CarbonMonoxideDetectorsNotes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var completedOn = runtimeEntityType.AddProperty(
                "CompletedOn",
                typeof(DateTime),
                propertyInfo: typeof(Inspection).GetProperty("CompletedOn", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<CompletedOn>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            var createdBy = runtimeEntityType.AddProperty(
                "CreatedBy",
                typeof(string),
                propertyInfo: typeof(BaseModel).GetProperty("CreatedBy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseModel).GetField("<CreatedBy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);

            var createdOn = runtimeEntityType.AddProperty(
                "CreatedOn",
                typeof(DateTime),
                propertyInfo: typeof(BaseModel).GetProperty("CreatedOn", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseModel).GetField("<CreatedOn>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            var documentId = runtimeEntityType.AddProperty(
                "DocumentId",
                typeof(Guid?),
                propertyInfo: typeof(Inspection).GetProperty("DocumentId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<DocumentId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var electricalSystemGood = runtimeEntityType.AddProperty(
                "ElectricalSystemGood",
                typeof(bool),
                propertyInfo: typeof(Inspection).GetProperty("ElectricalSystemGood", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<ElectricalSystemGood>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var electricalSystemNotes = runtimeEntityType.AddProperty(
                "ElectricalSystemNotes",
                typeof(string),
                propertyInfo: typeof(Inspection).GetProperty("ElectricalSystemNotes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<ElectricalSystemNotes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var exteriorDoorsGood = runtimeEntityType.AddProperty(
                "ExteriorDoorsGood",
                typeof(bool),
                propertyInfo: typeof(Inspection).GetProperty("ExteriorDoorsGood", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<ExteriorDoorsGood>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var exteriorDoorsNotes = runtimeEntityType.AddProperty(
                "ExteriorDoorsNotes",
                typeof(string),
                propertyInfo: typeof(Inspection).GetProperty("ExteriorDoorsNotes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<ExteriorDoorsNotes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var exteriorFoundationGood = runtimeEntityType.AddProperty(
                "ExteriorFoundationGood",
                typeof(bool),
                propertyInfo: typeof(Inspection).GetProperty("ExteriorFoundationGood", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<ExteriorFoundationGood>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var exteriorFoundationNotes = runtimeEntityType.AddProperty(
                "ExteriorFoundationNotes",
                typeof(string),
                propertyInfo: typeof(Inspection).GetProperty("ExteriorFoundationNotes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<ExteriorFoundationNotes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var exteriorGuttersGood = runtimeEntityType.AddProperty(
                "ExteriorGuttersGood",
                typeof(bool),
                propertyInfo: typeof(Inspection).GetProperty("ExteriorGuttersGood", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<ExteriorGuttersGood>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var exteriorGuttersNotes = runtimeEntityType.AddProperty(
                "ExteriorGuttersNotes",
                typeof(string),
                propertyInfo: typeof(Inspection).GetProperty("ExteriorGuttersNotes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<ExteriorGuttersNotes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var exteriorRoofGood = runtimeEntityType.AddProperty(
                "ExteriorRoofGood",
                typeof(bool),
                propertyInfo: typeof(Inspection).GetProperty("ExteriorRoofGood", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<ExteriorRoofGood>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var exteriorRoofNotes = runtimeEntityType.AddProperty(
                "ExteriorRoofNotes",
                typeof(string),
                propertyInfo: typeof(Inspection).GetProperty("ExteriorRoofNotes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<ExteriorRoofNotes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var exteriorSidingGood = runtimeEntityType.AddProperty(
                "ExteriorSidingGood",
                typeof(bool),
                propertyInfo: typeof(Inspection).GetProperty("ExteriorSidingGood", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<ExteriorSidingGood>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var exteriorSidingNotes = runtimeEntityType.AddProperty(
                "ExteriorSidingNotes",
                typeof(string),
                propertyInfo: typeof(Inspection).GetProperty("ExteriorSidingNotes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<ExteriorSidingNotes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var exteriorWindowsGood = runtimeEntityType.AddProperty(
                "ExteriorWindowsGood",
                typeof(bool),
                propertyInfo: typeof(Inspection).GetProperty("ExteriorWindowsGood", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<ExteriorWindowsGood>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var exteriorWindowsNotes = runtimeEntityType.AddProperty(
                "ExteriorWindowsNotes",
                typeof(string),
                propertyInfo: typeof(Inspection).GetProperty("ExteriorWindowsNotes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<ExteriorWindowsNotes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var generalNotes = runtimeEntityType.AddProperty(
                "GeneralNotes",
                typeof(string),
                propertyInfo: typeof(Inspection).GetProperty("GeneralNotes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<GeneralNotes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2000);

            var hvacSystemGood = runtimeEntityType.AddProperty(
                "HvacSystemGood",
                typeof(bool),
                propertyInfo: typeof(Inspection).GetProperty("HvacSystemGood", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<HvacSystemGood>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var hvacSystemNotes = runtimeEntityType.AddProperty(
                "HvacSystemNotes",
                typeof(string),
                propertyInfo: typeof(Inspection).GetProperty("HvacSystemNotes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<HvacSystemNotes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var inspectedBy = runtimeEntityType.AddProperty(
                "InspectedBy",
                typeof(string),
                propertyInfo: typeof(Inspection).GetProperty("InspectedBy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<InspectedBy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);

            var inspectionType = runtimeEntityType.AddProperty(
                "InspectionType",
                typeof(string),
                propertyInfo: typeof(Inspection).GetProperty("InspectionType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<InspectionType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 50);

            var interiorCeilingsGood = runtimeEntityType.AddProperty(
                "InteriorCeilingsGood",
                typeof(bool),
                propertyInfo: typeof(Inspection).GetProperty("InteriorCeilingsGood", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<InteriorCeilingsGood>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var interiorCeilingsNotes = runtimeEntityType.AddProperty(
                "InteriorCeilingsNotes",
                typeof(string),
                propertyInfo: typeof(Inspection).GetProperty("InteriorCeilingsNotes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<InteriorCeilingsNotes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var interiorDoorsGood = runtimeEntityType.AddProperty(
                "InteriorDoorsGood",
                typeof(bool),
                propertyInfo: typeof(Inspection).GetProperty("InteriorDoorsGood", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<InteriorDoorsGood>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var interiorDoorsNotes = runtimeEntityType.AddProperty(
                "InteriorDoorsNotes",
                typeof(string),
                propertyInfo: typeof(Inspection).GetProperty("InteriorDoorsNotes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<InteriorDoorsNotes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var interiorFloorsGood = runtimeEntityType.AddProperty(
                "InteriorFloorsGood",
                typeof(bool),
                propertyInfo: typeof(Inspection).GetProperty("InteriorFloorsGood", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<InteriorFloorsGood>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var interiorFloorsNotes = runtimeEntityType.AddProperty(
                "InteriorFloorsNotes",
                typeof(string),
                propertyInfo: typeof(Inspection).GetProperty("InteriorFloorsNotes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<InteriorFloorsNotes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var interiorWallsGood = runtimeEntityType.AddProperty(
                "InteriorWallsGood",
                typeof(bool),
                propertyInfo: typeof(Inspection).GetProperty("InteriorWallsGood", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<InteriorWallsGood>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var interiorWallsNotes = runtimeEntityType.AddProperty(
                "InteriorWallsNotes",
                typeof(string),
                propertyInfo: typeof(Inspection).GetProperty("InteriorWallsNotes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<InteriorWallsNotes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var interiorWindowsGood = runtimeEntityType.AddProperty(
                "InteriorWindowsGood",
                typeof(bool),
                propertyInfo: typeof(Inspection).GetProperty("InteriorWindowsGood", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<InteriorWindowsGood>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var interiorWindowsNotes = runtimeEntityType.AddProperty(
                "InteriorWindowsNotes",
                typeof(string),
                propertyInfo: typeof(Inspection).GetProperty("InteriorWindowsNotes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<InteriorWindowsNotes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var isDeleted = runtimeEntityType.AddProperty(
                "IsDeleted",
                typeof(bool),
                propertyInfo: typeof(BaseModel).GetProperty("IsDeleted", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseModel).GetField("<IsDeleted>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var isSampleData = runtimeEntityType.AddProperty(
                "IsSampleData",
                typeof(bool),
                propertyInfo: typeof(BaseModel).GetProperty("IsSampleData", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseModel).GetField("<IsSampleData>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var kitchenAppliancesGood = runtimeEntityType.AddProperty(
                "KitchenAppliancesGood",
                typeof(bool),
                propertyInfo: typeof(Inspection).GetProperty("KitchenAppliancesGood", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<KitchenAppliancesGood>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var kitchenAppliancesNotes = runtimeEntityType.AddProperty(
                "KitchenAppliancesNotes",
                typeof(string),
                propertyInfo: typeof(Inspection).GetProperty("KitchenAppliancesNotes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<KitchenAppliancesNotes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var kitchenCabinetsGood = runtimeEntityType.AddProperty(
                "KitchenCabinetsGood",
                typeof(bool),
                propertyInfo: typeof(Inspection).GetProperty("KitchenCabinetsGood", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<KitchenCabinetsGood>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var kitchenCabinetsNotes = runtimeEntityType.AddProperty(
                "KitchenCabinetsNotes",
                typeof(string),
                propertyInfo: typeof(Inspection).GetProperty("KitchenCabinetsNotes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<KitchenCabinetsNotes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var kitchenCountersGood = runtimeEntityType.AddProperty(
                "KitchenCountersGood",
                typeof(bool),
                propertyInfo: typeof(Inspection).GetProperty("KitchenCountersGood", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<KitchenCountersGood>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var kitchenCountersNotes = runtimeEntityType.AddProperty(
                "KitchenCountersNotes",
                typeof(string),
                propertyInfo: typeof(Inspection).GetProperty("KitchenCountersNotes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<KitchenCountersNotes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var kitchenSinkPlumbingGood = runtimeEntityType.AddProperty(
                "KitchenSinkPlumbingGood",
                typeof(bool),
                propertyInfo: typeof(Inspection).GetProperty("KitchenSinkPlumbingGood", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<KitchenSinkPlumbingGood>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var kitchenSinkPlumbingNotes = runtimeEntityType.AddProperty(
                "KitchenSinkPlumbingNotes",
                typeof(string),
                propertyInfo: typeof(Inspection).GetProperty("KitchenSinkPlumbingNotes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<KitchenSinkPlumbingNotes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var landscapingGood = runtimeEntityType.AddProperty(
                "LandscapingGood",
                typeof(bool),
                propertyInfo: typeof(Inspection).GetProperty("LandscapingGood", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<LandscapingGood>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var landscapingNotes = runtimeEntityType.AddProperty(
                "LandscapingNotes",
                typeof(string),
                propertyInfo: typeof(Inspection).GetProperty("LandscapingNotes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<LandscapingNotes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var lastModifiedBy = runtimeEntityType.AddProperty(
                "LastModifiedBy",
                typeof(string),
                propertyInfo: typeof(BaseModel).GetProperty("LastModifiedBy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseModel).GetField("<LastModifiedBy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);

            var lastModifiedOn = runtimeEntityType.AddProperty(
                "LastModifiedOn",
                typeof(DateTime?),
                propertyInfo: typeof(BaseModel).GetProperty("LastModifiedOn", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseModel).GetField("<LastModifiedOn>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var leaseId = runtimeEntityType.AddProperty(
                "LeaseId",
                typeof(Guid?),
                propertyInfo: typeof(Inspection).GetProperty("LeaseId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<LeaseId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var organizationId = runtimeEntityType.AddProperty(
                "OrganizationId",
                typeof(Guid),
                propertyInfo: typeof(BaseModel).GetProperty("OrganizationId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseModel).GetField("<OrganizationId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));

            var overallCondition = runtimeEntityType.AddProperty(
                "OverallCondition",
                typeof(string),
                propertyInfo: typeof(Inspection).GetProperty("OverallCondition", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<OverallCondition>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 20);

            var plumbingSystemGood = runtimeEntityType.AddProperty(
                "PlumbingSystemGood",
                typeof(bool),
                propertyInfo: typeof(Inspection).GetProperty("PlumbingSystemGood", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<PlumbingSystemGood>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var plumbingSystemNotes = runtimeEntityType.AddProperty(
                "PlumbingSystemNotes",
                typeof(string),
                propertyInfo: typeof(Inspection).GetProperty("PlumbingSystemNotes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<PlumbingSystemNotes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var propertyId = runtimeEntityType.AddProperty(
                "PropertyId",
                typeof(Guid),
                propertyInfo: typeof(Inspection).GetProperty("PropertyId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<PropertyId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));

            var smokeDetectorsGood = runtimeEntityType.AddProperty(
                "SmokeDetectorsGood",
                typeof(bool),
                propertyInfo: typeof(Inspection).GetProperty("SmokeDetectorsGood", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<SmokeDetectorsGood>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var smokeDetectorsNotes = runtimeEntityType.AddProperty(
                "SmokeDetectorsNotes",
                typeof(string),
                propertyInfo: typeof(Inspection).GetProperty("SmokeDetectorsNotes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<SmokeDetectorsNotes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { completedOn });

            var index0 = runtimeEntityType.AddIndex(
                new[] { documentId });

            var index1 = runtimeEntityType.AddIndex(
                new[] { leaseId });

            var index2 = runtimeEntityType.AddIndex(
                new[] { propertyId });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("DocumentId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.SetNull);

            var document = declaringEntityType.AddNavigation("Document",
                runtimeForeignKey,
                onDependent: true,
                typeof(Document),
                propertyInfo: typeof(Inspection).GetProperty("Document", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<Document>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("LeaseId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.SetNull);

            var lease = declaringEntityType.AddNavigation("Lease",
                runtimeForeignKey,
                onDependent: true,
                typeof(Lease),
                propertyInfo: typeof(Inspection).GetProperty("Lease", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<Lease>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey3(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("PropertyId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            var property = declaringEntityType.AddNavigation("Property",
                runtimeForeignKey,
                onDependent: true,
                typeof(Property),
                propertyInfo: typeof(Inspection).GetProperty("Property", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Inspection).GetField("<Property>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Inspections");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
