// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Aquiis.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Aquiis.Infrastructure.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class RentalApplicationEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Aquiis.Core.Entities.RentalApplication",
                typeof(RentalApplication),
                baseEntityType,
                propertyCount: 37,
                navigationCount: 3,
                foreignKeyCount: 2,
                unnamedIndexCount: 5,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(BaseModel).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseModel).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));

            var applicationFee = runtimeEntityType.AddProperty(
                "ApplicationFee",
                typeof(decimal),
                propertyInfo: typeof(RentalApplication).GetProperty("ApplicationFee", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<ApplicationFee>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                precision: 18,
                scale: 2,
                sentinel: 0m);
            applicationFee.AddAnnotation("Relational:ColumnType", "decimal(18,2)");

            var applicationFeePaid = runtimeEntityType.AddProperty(
                "ApplicationFeePaid",
                typeof(bool),
                propertyInfo: typeof(RentalApplication).GetProperty("ApplicationFeePaid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<ApplicationFeePaid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var applicationFeePaidOn = runtimeEntityType.AddProperty(
                "ApplicationFeePaidOn",
                typeof(DateTime?),
                propertyInfo: typeof(RentalApplication).GetProperty("ApplicationFeePaidOn", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<ApplicationFeePaidOn>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var applicationFeePaymentMethod = runtimeEntityType.AddProperty(
                "ApplicationFeePaymentMethod",
                typeof(string),
                propertyInfo: typeof(RentalApplication).GetProperty("ApplicationFeePaymentMethod", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<ApplicationFeePaymentMethod>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50);

            var appliedOn = runtimeEntityType.AddProperty(
                "AppliedOn",
                typeof(DateTime),
                propertyInfo: typeof(RentalApplication).GetProperty("AppliedOn", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<AppliedOn>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            var createdBy = runtimeEntityType.AddProperty(
                "CreatedBy",
                typeof(string),
                propertyInfo: typeof(BaseModel).GetProperty("CreatedBy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseModel).GetField("<CreatedBy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);

            var createdOn = runtimeEntityType.AddProperty(
                "CreatedOn",
                typeof(DateTime),
                propertyInfo: typeof(BaseModel).GetProperty("CreatedOn", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseModel).GetField("<CreatedOn>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            var currentAddress = runtimeEntityType.AddProperty(
                "CurrentAddress",
                typeof(string),
                propertyInfo: typeof(RentalApplication).GetProperty("CurrentAddress", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<CurrentAddress>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 200);

            var currentCity = runtimeEntityType.AddProperty(
                "CurrentCity",
                typeof(string),
                propertyInfo: typeof(RentalApplication).GetProperty("CurrentCity", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<CurrentCity>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);

            var currentRent = runtimeEntityType.AddProperty(
                "CurrentRent",
                typeof(decimal),
                propertyInfo: typeof(RentalApplication).GetProperty("CurrentRent", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<CurrentRent>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                precision: 18,
                scale: 2,
                sentinel: 0m);
            currentRent.AddAnnotation("Relational:ColumnType", "decimal(18,2)");

            var currentState = runtimeEntityType.AddProperty(
                "CurrentState",
                typeof(string),
                propertyInfo: typeof(RentalApplication).GetProperty("CurrentState", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<CurrentState>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 2);

            var currentZipCode = runtimeEntityType.AddProperty(
                "CurrentZipCode",
                typeof(string),
                propertyInfo: typeof(RentalApplication).GetProperty("CurrentZipCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<CurrentZipCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 10);

            var decidedOn = runtimeEntityType.AddProperty(
                "DecidedOn",
                typeof(DateTime?),
                propertyInfo: typeof(RentalApplication).GetProperty("DecidedOn", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<DecidedOn>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var decisionBy = runtimeEntityType.AddProperty(
                "DecisionBy",
                typeof(string),
                propertyInfo: typeof(RentalApplication).GetProperty("DecisionBy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<DecisionBy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);

            var denialReason = runtimeEntityType.AddProperty(
                "DenialReason",
                typeof(string),
                propertyInfo: typeof(RentalApplication).GetProperty("DenialReason", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<DenialReason>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 1000);

            var employerName = runtimeEntityType.AddProperty(
                "EmployerName",
                typeof(string),
                propertyInfo: typeof(RentalApplication).GetProperty("EmployerName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<EmployerName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 200);

            var employmentLengthMonths = runtimeEntityType.AddProperty(
                "EmploymentLengthMonths",
                typeof(int),
                propertyInfo: typeof(RentalApplication).GetProperty("EmploymentLengthMonths", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<EmploymentLengthMonths>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);

            var expiresOn = runtimeEntityType.AddProperty(
                "ExpiresOn",
                typeof(DateTime?),
                propertyInfo: typeof(RentalApplication).GetProperty("ExpiresOn", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<ExpiresOn>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var isDeleted = runtimeEntityType.AddProperty(
                "IsDeleted",
                typeof(bool),
                propertyInfo: typeof(BaseModel).GetProperty("IsDeleted", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseModel).GetField("<IsDeleted>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var isSampleData = runtimeEntityType.AddProperty(
                "IsSampleData",
                typeof(bool),
                propertyInfo: typeof(BaseModel).GetProperty("IsSampleData", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseModel).GetField("<IsSampleData>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var jobTitle = runtimeEntityType.AddProperty(
                "JobTitle",
                typeof(string),
                propertyInfo: typeof(RentalApplication).GetProperty("JobTitle", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<JobTitle>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);

            var landlordName = runtimeEntityType.AddProperty(
                "LandlordName",
                typeof(string),
                propertyInfo: typeof(RentalApplication).GetProperty("LandlordName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<LandlordName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 200);

            var landlordPhone = runtimeEntityType.AddProperty(
                "LandlordPhone",
                typeof(string),
                propertyInfo: typeof(RentalApplication).GetProperty("LandlordPhone", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<LandlordPhone>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 20);

            var lastModifiedBy = runtimeEntityType.AddProperty(
                "LastModifiedBy",
                typeof(string),
                propertyInfo: typeof(BaseModel).GetProperty("LastModifiedBy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseModel).GetField("<LastModifiedBy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);

            var lastModifiedOn = runtimeEntityType.AddProperty(
                "LastModifiedOn",
                typeof(DateTime?),
                propertyInfo: typeof(BaseModel).GetProperty("LastModifiedOn", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseModel).GetField("<LastModifiedOn>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var monthlyIncome = runtimeEntityType.AddProperty(
                "MonthlyIncome",
                typeof(decimal),
                propertyInfo: typeof(RentalApplication).GetProperty("MonthlyIncome", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<MonthlyIncome>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                precision: 18,
                scale: 2,
                sentinel: 0m);
            monthlyIncome.AddAnnotation("Relational:ColumnType", "decimal(18,2)");

            var organizationId = runtimeEntityType.AddProperty(
                "OrganizationId",
                typeof(Guid),
                propertyInfo: typeof(BaseModel).GetProperty("OrganizationId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseModel).GetField("<OrganizationId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));

            var propertyId = runtimeEntityType.AddProperty(
                "PropertyId",
                typeof(Guid),
                propertyInfo: typeof(RentalApplication).GetProperty("PropertyId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<PropertyId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));

            var prospectiveTenantId = runtimeEntityType.AddProperty(
                "ProspectiveTenantId",
                typeof(Guid),
                propertyInfo: typeof(RentalApplication).GetProperty("ProspectiveTenantId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<ProspectiveTenantId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));

            var reference1Name = runtimeEntityType.AddProperty(
                "Reference1Name",
                typeof(string),
                propertyInfo: typeof(RentalApplication).GetProperty("Reference1Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<Reference1Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 200);

            var reference1Phone = runtimeEntityType.AddProperty(
                "Reference1Phone",
                typeof(string),
                propertyInfo: typeof(RentalApplication).GetProperty("Reference1Phone", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<Reference1Phone>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 20);

            var reference1Relationship = runtimeEntityType.AddProperty(
                "Reference1Relationship",
                typeof(string),
                propertyInfo: typeof(RentalApplication).GetProperty("Reference1Relationship", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<Reference1Relationship>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);

            var reference2Name = runtimeEntityType.AddProperty(
                "Reference2Name",
                typeof(string),
                propertyInfo: typeof(RentalApplication).GetProperty("Reference2Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<Reference2Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 200);

            var reference2Phone = runtimeEntityType.AddProperty(
                "Reference2Phone",
                typeof(string),
                propertyInfo: typeof(RentalApplication).GetProperty("Reference2Phone", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<Reference2Phone>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 20);

            var reference2Relationship = runtimeEntityType.AddProperty(
                "Reference2Relationship",
                typeof(string),
                propertyInfo: typeof(RentalApplication).GetProperty("Reference2Relationship", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<Reference2Relationship>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);

            var status = runtimeEntityType.AddProperty(
                "Status",
                typeof(string),
                propertyInfo: typeof(RentalApplication).GetProperty("Status", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<Status>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 50);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { appliedOn });

            var index0 = runtimeEntityType.AddIndex(
                new[] { organizationId });

            var index1 = runtimeEntityType.AddIndex(
                new[] { propertyId });

            var index2 = runtimeEntityType.AddIndex(
                new[] { prospectiveTenantId });

            var index3 = runtimeEntityType.AddIndex(
                new[] { status });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("PropertyId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            var property = declaringEntityType.AddNavigation("Property",
                runtimeForeignKey,
                onDependent: true,
                typeof(Property),
                propertyInfo: typeof(RentalApplication).GetProperty("Property", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<Property>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ProspectiveTenantId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            var prospectiveTenant = declaringEntityType.AddNavigation("ProspectiveTenant",
                runtimeForeignKey,
                onDependent: true,
                typeof(ProspectiveTenant),
                propertyInfo: typeof(RentalApplication).GetProperty("ProspectiveTenant", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RentalApplication).GetField("<ProspectiveTenant>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var applications = principalEntityType.AddNavigation("Applications",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<RentalApplication>),
                propertyInfo: typeof(ProspectiveTenant).GetProperty("Applications", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProspectiveTenant).GetField("<Applications>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "RentalApplications");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
